import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faAddressCard,
  faArrowLeft,
  faArrowRight,
  faBan,
  faBars,
  faBell,
  faCartShopping,
  faDroplet,
  faEye,
  faHeart,
  faHouse,
  faLanguage,
  faListCheck,
  faMinus,
  faPencilAlt,
  faPlay,
  faPlus,
  faRightToBracket,
  faSave,
  faSignInAlt,
  faSignOutAlt,
  faSort,
  faSpinner,
  faStairs,
  faStar,
  faStore,
  faSync,
  faTasks,
  faTrash,
  faUser,
  faUserShield,
  faX,
} from '@fortawesome/free-solid-svg-icons';
import { faProductHunt, faGoogle } from '@fortawesome/free-brands-svg-icons';

export const loadIcon = () => {
  library.add(
    faArrowLeft,
    faArrowRight,
    faSignInAlt,
    faSignOutAlt,
    faPlus,
    faMinus,
    faTasks,
    faTrash,
    faUser,
    faPlay,
    faSpinner,
    faBars,
    faX,
    faUserShield,
    faHouse,
    faAddressCard,
    faBell,
    faDroplet,
    faStore,
    faRightToBracket,
    faCartShopping,
    faHeart,
    faProductHunt,
    faSort,
    faHeart,
    faGoogle,
    faSync,
    faEye,
    faPencilAlt,
    faBan,
    faSave,
    faListCheck,
    faLanguage,
    faStar,
    faStairs
    // Add more icons here
  );
};
